openapi: 3.0.0
info:
  title: API de Animes
  description: Uma API RESTful desenvolvida para fornecer informações sobre animes. Este projeto foi criado como parte de um trabalho da disciplina de Desenvolvimento Web e tem como objetivo praticar a criação e consumo de APIs.
  version: 1.0.0
servers:
  - url: http://localhost:4000/api/animes
    description: Servidor local
paths:
  /animes:
    get:
      tags:
        - Animes
      summary: Retorna a lista de todos os animes cadastrados
      responses:
        '200':
          description: Lista de animes obtida com sucesso.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Anime'
        '500':
          description: Erro interno do servidor.
    post:
      tags:
        - Animes
      summary: Cria um novo registro de anime
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnimeInput'
      responses:
        '201':
          description: Anime criado com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Anime'
        '400':
          description: Dados de entrada inválidos.
  /animes/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
        description: ID do anime a ser buscado (geralmente um ID do MongoDB).
    get:
      tags:
        - Animes
      summary: Retorna um anime específico pelo ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID do anime a ser buscado (geralmente um ID do MongoDB).
      responses:
        '200':
          description: Detalhes do anime.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Anime'
              examples:
                exemplo:
                  value:
                    id: 60d5ec49f6a5b4001c9a0b1c
                    title: "Attack on Titan"
                    type: "TV"
                    episodes_count: "25"
                    studio: ["Wit Studio", "MAPPA"]
                    genres: ["Ação", "Shonen"]
                    rating: "9.1"
                    dub: ["pt-BR", "en"]
                    sub: ["pt-BR", "en"]
                    imageUrl: ["https://cdn.com/anime1.jpg"]
                    descriptions:
                      - synopsis: "A humanidade vive protegida por muros gigantes..."
                        background: "Baseado no mangá de Hajime Isayama."
                        tags: ["ação", "drama"]
        '404':
          description: Anime não encontrado.
        '400':
          description: ID inválido fornecido.
    put:
      tags:
        - Animes
      summary: Atualiza um anime existente
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID do anime a ser atualizado (geralmente um ID do MongoDB).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnimeInput'
            examples:
              exemplo:
                value:
                  title: "Jujutsu Kaisen"
                  type: "TV"
                  episodes_count: "24"
                  studio: ["MAPPA"]
                  genres: ["Aventura", "Sobrenatural"]
                  rating: "8.9"
                  dub: ["pt-BR"]
                  sub: ["pt-BR"]
                  imageUrl: ["https://cdn.com/jujutsu.jpg"]
                  descriptions:
                    - synopsis: "Itadori Yuji é um estudante do ensino médio..."
                      background: "Baseado no mangá de Gege Akutami."
                      tags: ["ação", "sobrenatural"]
      responses:
        '200':
          description: Anime atualizado com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Anime'
        '404':
          description: Anime não encontrado.
        '400':
          description: ID inválido fornecido.
    delete:
      tags:
        - Animes
      summary: Remove um anime pelo ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID do anime a ser removido (geralmente um ID do MongoDB).
      responses:
        '204':
          description: Anime removido com sucesso. (No Content)
        '404':
          description: Anime não encontrado.
        '400':
          description: ID inválido fornecido.
components:
  schemas:
    Anime:
      type: object
      description: Modelo de dados de um anime, incluindo o ID após a criação.
      properties:
        id:
          type: string
          description: 'ID gerado automaticamente (ex: MongoDB ObjectId).'
          example: 60d5ec49f6a5b4001c9a0b1c
        title:
          type: string
          description: Nome do anime.
          example: Attack on Titan
        type:
          type: string
          description: Tipo do anime (TV, Filme, OVA, etc).
          example: TV
        episodes_count:
          type: string
          description: Quantidade total de episódios (somando todas as temporadas). Exemplo: "2 temporadas, 24 episódios".
          example: "2 temporadas, 24 episódios"
        studio:
          type: array
          items:
            type: string
          description: Lista de estúdios.
          example: ["Wit Studio", "MAPPA"]
        genres:
          type: array
          items:
            type: string
          description: Lista de gêneros.
          example: ["Ação", "Shonen"]
        rating:
          type: string
          description: Classificação indicativa do anime (ex: "14", "18", "Livre").
          example: "14"
        dub:
          type: array
          items:
            type: string
          description: Idiomas de dublagem disponíveis.
          example: ["pt-BR", "en"]
        sub:
          type: array
          items:
            type: string
          description: Idiomas de legenda disponíveis.
          example: ["pt-BR", "en"]
        imageUrl:
          type: array
          items:
            type: string
          description: URLs das imagens do anime.
          example: ["https://cdn.com/anime1.jpg"]
        descriptions:
          type: array
          items:
            type: object
            properties:
              synopsis:
                type: string
                description: Sinopse do anime.
                example: "A humanidade vive protegida por muros gigantes..."
              background:
                type: string
                description: Contexto de fundo do anime.
                example: "Baseado no mangá de Hajime Isayama."
              tags:
                type: array
                items:
                  type: string
                description: Lista de tags.
                example: ["ação", "drama"]
      required:
        - title
        - genres
        - studio

    AnimeInput:
      type: object
      description: Dados necessários para criar ou atualizar um anime. Não inclui o ID.
      properties:
        title:
          type: string
          description: Nome do anime.
          example: Jujutsu Kaisen
        type:
          type: string
          description: Tipo do anime.
          example: TV
        episodes_count:
          type: string
          description: Quantidade total de episódios (somando todas as temporadas). Exemplo: "2 temporadas, 24 episódios".
          example: "2 temporadas, 24 episódios"
        studio:
          type: array
          items:
            type: string
          description: Lista de estúdios.
          example: ["MAPPA"]
        genres:
          type: array
          items:
            type: string
          description: Lista de gêneros.
          example: ["Aventura", "Sobrenatural"]
        rating:
          type: string
          description: Classificação indicativa do anime (ex: "14", "18", "Livre").
          example: "14"
        dub:
          type: array
          items:
            type: string
          description: Idiomas de dublagem disponíveis.
          example: ["pt-BR"]
        sub:
          type: array
          items:
            type: string
          description: Idiomas de legenda disponíveis.
          example: ["pt-BR"]
        imageUrl:
          type: array
          items:
            type: string
          description: URLs das imagens do anime.
          example: ["https://cdn.com/jujutsu.jpg"]
        descriptions:
          type: array
          items:
            type: object
            properties:
              synopsis:
                type: string
                description: Sinopse do anime.
                example: "Itadori Yuji é um estudante do ensino médio..."
              background:
                type: string
                description: Contexto de fundo do anime.
                example: "Baseado no mangá de Gege Akutami."
              tags:
                type: array
                items:
                  type: string
                description: Lista de tags.
                example: ["ação", "sobrenatural"]
      required:
        - title
        - genres
        - studio